version: '3'

networks:
  backend_network:
    ipam:
      config:
        - subnet: 172.80.0.1/16
          gateway: 172.80.0.1

services:

  frontend:
    image: frontend
    ports:
      - 3000:80
  backend:
    container_name: backend
    image: backend
    depends_on:
      - database
    ports:
      - "8008:8008"
    networks:
      backend_network:
        ipv4_address: 172.80.0.2

  database:
    image: "postgres:latest"
    networks:
      backend_network:
        ipv4_address: 172.80.0.3
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
    volumes:
      - ./database:/var/lib/postgresql/database





# services:
#   database:
#     image: "postgres:latest"
#     ports:
#       - "5432:5432"
#     environment:
#       POSTGRES_USER: admin
#       POSTGRES_PASSWORD: admin
#       POSTGRES_DB: postgres
#     volumes:
#       - ./database:/var/lib/postgresql/database