PUT http://localhost:8008/api/blog/edit/comment
Content-Type: application/json

{
  "id":4,
  "index": 0,
  "comment": "Take care!"
}

###
POST http://localhost:8008/api/blog/update/views
Content-Type: application/json

{
  "blogId": 2,
  "userId": 1
}

###
GET http://localhost:8008/api/blog/get/allblogs
Accept: application/json

###

POST http://localhost:8008/api/blog/update/views?blogId=2&userId=2
Accept: application/json

###
DELETE http://localhost:8008/api/blog/delete/comment
Content-Type: application/json

{
  "Id": 2,
  "index": 0,
  "user_Id": 1
}

###

POST http://localhost:8008/api/blog/add/comment
Content-Type: application/json

{
  "Id": 4,
  "user_Id": 1,
  "comments": "Looks good Man!"
}

###

GET http://localhost:8008/api/account/get/allblogsbyid?Id=1
Accept: application/json

###


PUT http://localhost:8008/api/blog/edit
Content-Type: application/json

{
  "Id": 2,
  "title": "HELLO YOU!",
  "body": "Loving is hard."
}

###

DELETE http://localhost:8008/api/account/delete/blog?ownerId=1&blogId=2
Accept: application/json

###

POST http://localhost:8008/api/account/post/blog
Content-Type: application/json

{
  "title": "Test5!",
  "body": "Waking up everyday, it's great.",
  "owner_Email": "test1",
  "owner_Id": 1
}

###
