POST http://localhost:8008/api/account/sendMessage
Content-Type: application/json

{
  "current_Id": 1,
  "message": "HELLO WORLD",
  "sender_Id": 2
}

###
GET http://localhost:8008/api/account/login?email=1142&password=12345
Accept: application/json

###
POST http://localhost:8008/api/account
Content-Type: application/json

{
  "email": "11422",
  "password": "12345",
  "confirm_Password": "12345",
  "name":"Kongmeng"
}

###
